// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ajuste_Tipo_Field_Fabricante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajuste_Tipo_Field_Fabricante));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180059096_Ajuste_Tipo_Field_Fabricante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
