// <auto-generated />
namespace Persistencia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Field_Categoria_Remove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Field_Categoria_Remove));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180124295_Field_Categoria_Remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
